name: TechFatafat Shorts Automation

on:
  schedule:
    - cron: "0 18 * * *"  # 6PM UTC daily
  workflow_dispatch:
    inputs:
      custom_topic:
        description: "Manual Topic (Optional)"
        required: false

jobs:
  create-short:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libimage-exiftool-perl fonts-dejavu
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run automation
        run: |
          python shorts_automator.py "${{ inputs.custom_topic }}"
        env:
          YOUTUBE_CREDENTIALS: ${{ secrets.YOUTUBE_CREDENTIALS }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          CHANNEL_NAME: "TechFatafat"
